Java: remove synchronized parts
scylladb/alternator-load-balancing pull request #42
Opened 2024-11-14 16:34 UTC by dkropachev

Using `CopyOnWriteArrayList` and `AtomicInteger` will provide more performance.

2024-11-14 17:50 UTC, Bouncheck requested changes

2024-11-14 17:50 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                node = liveNodes.get(nextLiveNodeIndex.addAndGet(1));
previously `nextLiveNodeIndex` would loop around to 0 on reaching `liveNodes.size()`. Now it will return unmodified `node` if out of bounds.

2024-11-14 17:50 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                node = liveNodes.get(nextLiveNodeIndex.addAndGet(1));
Also previously we would first get the node and then increment. This code first increments then gets the node. It's possible it's not important at all, but I'm not familiar with the rest of the repo.

2024-11-14 17:50 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                liveNodes.removeAll(toDelete);
I think this is harder to reason about and probably less efficient. Previous solution ensured whole `liveNodes` collection changes were sequential, so the last update would decide what `liveNodes` are.
Here we can have two `updateLiveNodes()` (assuming concurrent calls are allowed) race with each other and toAdd checks, toDelete checks, `addAll`, `removeAll` from two different calls can intertwine with each other.  `nextLiveNodeIndex` does not get updated too and can for example become out of bounds due to removal.

The complexity is also higher since add/remove operations require making a copy of `CopyOnWriteArrayList`. Previous swap with already created `newHosts` is likely simpler, but since there is probably not that many nodes the complexity does not matter much here.

2024-11-14 18:07 UTC, Bouncheck commented
What is the issue with synchronized? Old methods looks fine to me.

2024-11-14 18:17 UTC, nyh requested changes

2024-11-14 18:17 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                node = liveNodes.get(nextLiveNodeIndex.addAndGet(1));
When there is just a single node, nextNode() is supposed to return always 0, but in this code it will start by incrementing the 0 to 1, which doesn't exist, so it then goes into an infinite loop (actually, after 4 billion operations node will go back to zero and will work). So this code appears wrong.

2024-11-14 18:17 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                liveNodes.removeAll(toDelete);
I agree.  It's really odd that CopyOnWriteArrayList doesn't have a method to completely replace the list - which is our use case.
Seeing that, I think you can and should replace your CopyOnWriteArrayList-based solution by a solution based on AtomicReference. Our list will be an AtomicReference so you can just read from it without a lock, and the update code will simply replace the reference by the new list.

2024-11-14 18:37 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                node = liveNodes.get(nextLiveNodeIndex.addAndGet(1));
My bad, take a look again, now it is `% size` so, it will return 0 in such case.

2024-11-14 18:41 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                liveNodes.removeAll(toDelete);
Good call, done, take a look, indeed it looks so much better.

2024-11-14 18:42 UTC, dkropachev commented
@nyh, @Bouncheck , please check one more time.

2024-11-14 18:56 UTC, nyh approved these changes
Looks good to me although I doubt the old syncrhonization-based code ever caused any user performance problems.
By the way, I wonder how important it is to diligently go round-robin on a multi-core machine. We could have also had a per-cpu nextLiveNodeIndex instead of trying to use atomic increments (which aren't as slow as synch, but still comparably slow). But I don't think we should worry about that.

2024-11-14 18:56 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +import java.util.concurrent.CopyOnWriteArrayList;
This is no longer needed in the new version

2024-11-14 18:57 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        List<String> newHosts = new ArrayList<>();
I'm curious why, or even how, you changed this. Is this new Java syntax? How can the new guess this is to be a list of strings?

2024-11-14 18:58 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                Collections.sort(newHosts);
I didn't see this in my earlier review, I guess you keep modifying this file or I just missed it?
Why add this sort? What order does it sort by? Why is this good / interesting / useful?

2024-11-14 19:56 UTC, Bouncheck approved these changes
LGTM assuming we do not exceed max integer number of calls to nextNode().

`!liveNodes.get().equals(newHosts)` and sorting is unnecessary in my opinion. I'm guessing this is because you don't want to log that nodes were updated if they were reported to be the same as current `liveNodes`. I assume we don't refresh that often so the impact is negligible.

Changing `AtomicReference<T>` to `volatile T` is just an idea. I don't know if it matters that much either. We probably save a few bytes and one reference jump.

2024-11-14 19:56 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        String node = nodes.get(nextLiveNodeIndex.getAndIncrement() % nodes.size());
This is fine if we're sure there won't be more than `Integer.MAX_VALUE` (roughly 2*10^9) calls to this function. Otherwise we need an atomic long which hopefully will be enough. Or check for the negatives.

2024-11-14 19:56 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +    private final AtomicReference<List<String>> liveNodes;
I think you can do `private volatile List<String> liveNodes;` and when updating just do `liveNodes = newNodes`, assuming there are no modifications to `liveNodes` which seems there are not. Reference assignment is atomic in Java. In that case I'd also add a comment about thread safety, so that nobody in the future modifies this variable.

2024-11-14 19:56 UTC, Bouncheck commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        if (!newHosts.isEmpty() && !liveNodes.get().equals(newHosts)) {
This equals can be costly if nodes don't change. In that case it's probably just cheaper to set, since it's technically the same thing anyway.
Also see my comment above on liveNodes declaration: since we do only `get` and `set` then `volatile` should be good enough.

2024-11-14 20:12 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        String node = nodes.get(nextLiveNodeIndex.getAndIncrement() % nodes.size());
True, wrapped it with Math.abs()

2024-11-14 20:25 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        List<String> newHosts = new ArrayList<>();
It inferes it from the target type, just a way not to repeat your self.

2024-11-14 20:27 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +                Collections.sort(newHosts);
it was done to make compare work properly, but @Bouncheck is correct we can skip comparision and just replace it anyways, sparing couple hundreds of CPU cycles, so it is removed.

2024-11-14 20:27 UTC, merged

2024-11-14 21:03 UTC, dkropachev commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        if (!newHosts.isEmpty() && !liveNodes.get().equals(newHosts)) {
True, but code like:
```
tmp = liveNodes;
tmp.get(idx % tmp.size())
```
Looks more confusing than:
```
tmp = liveNodes.get()
tmp.get(idx % tmp.size())
```

2024-11-14 21:34 UTC, dkropachev commented
@Bouncheck , I somehow accidentially merged it, please let me know if you want to roll it back

2024-11-17 09:55 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        String node = nodes.get(Math.abs(nextLiveNodeIndex.getAndIncrement() % nodes.size()));
Wow, I forgot that Java's integers are always signed, and its "%" on signed integer is the screwy C-inspired implementation.
https://stackoverflow.com/questions/4412179/best-way-to-make-javas-modulus-behave-like-it-should-with-negative-numbers suggests using [Math.floorMod(int x, int y)](http://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#floorMod-int-int-)
You abs() approach works too, although it behaves in a funny way when the counter becomes negative, the round robin reverses direction :-) Which is fine, but weird.

2024-11-17 09:59 UTC, nyh commented on java/src/main/java/com/scylladb/alternator/AlternatorLiveNodes.java
> +        List<String> newHosts = new ArrayList<>();
Nice. I haven't used Java "seriously" for 15 years or so, so some of the newer stuff I haven't noticed :-)

2024-11-17 11:29 UTC, mykaul commented
Do we have numbers to show it improves performance?

2024-11-18 02:02 UTC, dkropachev commented
> Do we have numbers to show it improves performance?

Unfortunately java does not have built-in microbenchmark framework, and this repo does not have one as well.
So, having these test will require some effort.
I have created a naive benchmark that runs 100 threads, each thread runs `100000` `nextAsURI`, old version completes test in `2752` ms, while new one in `802`, so it is 3+ times faster in given circumstances.
To be fair this test does not represent real scenario, rather extreme case, but it showcase congestion that can be created by exclusive locks on class instance, which `sinchronize` is. 

Test:
```
package com.scylladb.alternator;

import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class AlternatorLiveNodesBenchmark {
    static public class MockAlternatorLiveNodes extends AlternatorLiveNodes {
        private MockAlternatorLiveNodes() {
            super("http", Arrays.asList("1.1.1.1"), 8080);
        }

        @Override
        List<String> getNodesListFromURL(URI uri) throws IOException {
            String[] tmp = {"1.1.1.2", "1.1.1.3", "1.1.1.4"};
            return Arrays.asList(tmp);
        }
    }

    public synchronized static void main(String[] args) {
        Integer threads = 100;
        Integer iterations = 100000;

        AlternatorLiveNodes ln = new MockAlternatorLiveNodes();
        ln.setDaemon(true);
        ln.start();
        List<Thread> th = new ArrayList<>();
        for (Integer n = 0; n < threads; n++) {
            th.add(new Thread(() -> {
                for (int i = 0; i < iterations; i++) {
                    URI tmp = ln.nextAsURI();
                }
            }));
        }
        long startTime = System.currentTimeMillis();
        th.forEach(Thread::start);
        th.forEach(t -> {
            try {
                t.join();
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
        long lasted = System.currentTimeMillis() - startTime;
        System.out.println(String.format("done waiting - lasted %s", lasted));
        System.exit(0);
    }
}
```